// Automatically generated

export interface ChartValues {
  chrome?: {
    chromeVersion?: any
    display?: any
    enabled?: any
    image?: any
    javaOpts?: any
    nodeMaxInstances?: any
    nodeMaxSession?: any
    nodePort?: any
    nodeRegisterCycle?: any
    nodeSelector?: any
    pullPolicy?: any
    replicas?: any
    resources?: any
    screenDepth?: any
    screenHeight?: any
    screenWidth?: any
    seOpts?: any
    tag?: any
    timeZone?: any
    volumeMounts?: any
    volumes?: any
  }
  chromeDebug?: {
    chromeVersion?: any
    display?: any
    enabled?: any
    image?: any
    javaOpts?: any
    nodeMaxInstances?: any
    nodeMaxSession?: any
    nodePort?: any
    nodeRegisterCycle?: any
    nodeSelector?: any
    pullPolicy?: any
    replicas?: any
    resources?: any
    screenDepth?: any
    screenHeight?: any
    screenWidth?: any
    seOpts?: any
    tag?: any
    timeZone?: any
    volumeMounts?: any
    volumes?: any
  }
  firefox?: {
    display?: any
    enabled?: any
    firefoxVersion?: any
    image?: any
    javaOpts?: any
    nodeMaxInstances?: any
    nodeMaxSession?: any
    nodePort?: any
    nodeRegisterCycle?: any
    nodeSelector?: any
    pullPolicy?: any
    replicas?: any
    resources?: any
    screenDepth?: any
    screenHeight?: any
    screenWidth?: any
    seOpts?: any
    tag?: any
    timeZone?: any
  }
  firefoxDebug?: {
    display?: any
    enabled?: any
    firefoxVersion?: any
    image?: any
    javaOpts?: any
    jmxPort?: any
    nodeMaxInstances?: any
    nodeMaxSession?: any
    nodePort?: any
    nodeRegisterCycle?: any
    nodeSelector?: any
    pullPolicy?: any
    replicas?: any
    resources?: any
    screenDepth?: any
    screenHeight?: any
    screenWidth?: any
    seOpts?: any
    tag?: any
    timeZone?: any
  }
  global?: {
    nodeSelector?: any
  }
  hub?: {
    gridBrowserTimeout?: any
    gridCleanUpCycle?: any
    gridJettyMaxThreads?: any
    gridMaxSession?: any
    gridNewSessionWaitTimeout?: any
    gridNodePolling?: any
    gridTimeout?: any
    gridUnregisterIfStillDownAfer?: any
    image?: any
    ingress?: {
      annotations?: any
      enabled?: any
      hosts?: any
      path?: any
      tls?: any
    }
    javaOpts?: any
    jmxPort?: any
    livenessTimeout?: any
    loadBalancerSourceRanges?: any
    nodeSelector?: any
    port?: any
    pullPolicy?: any
    readinessDelay?: any
    readinessTimeout?: any
    resources?: any
    seOpts?: any
    serviceAnnotations?: any
    serviceLoadBalancerIP?: any
    serviceSessionAffinity?: any
    serviceType?: any
    tag?: any
    timeZone?: any
  }
  nameOverride?: any
}

